In [7]:
# !pip install pandas

In [1]:
import sys
print(sys.executable)

/home/codespace/.python/current/bin/python


In [10]:
import os

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_parquet('yellow_tripdata_2024-01.parquet')

In [4]:
df.head()

VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0         2  2024-01-01 00:57:55   2024-01-01 01:17:43              1.0   
1         1  2024-01-01 00:03:00   2024-01-01 00:09:36              1.0   
2         1  2024-01-01 00:17:06   2024-01-01 00:35:01              1.0   
3         1  2024-01-01 00:36:38   2024-01-01 00:44:56              1.0   
4         1  2024-01-01 00:46:51   2024-01-01 00:52:57              1.0   

   trip_distance  RatecodeID store_and_fwd_flag  PULocationID  DOLocationID  \
0           1.72         1.0                  N           186            79   
1           1.80         1.0                  N           140           236   
2           4.70         1.0                  N           236            79   
3           1.40         1.0                  N            79           211   
4           0.80         1.0                  N           211           148   

   payment_type  fare_amount  extra  mta_tax  tip_amount  tolls_amount  \
0             2         17.7    1.0      0.5        0.00           0.0   
1             1         10.0    3.5      0.5        3.75           0.0   
2             1         23.3    3.5      0.5        3.00           0.0   
3             1         10.0    3.5      0.5        2.00           0.0   
4             1          7.9    3.5      0.5        3.20           0.0   

   improvement_surcharge  total_amount  congestion_surcharge  Airport_fee  
0                    1.0         22.70                   2.5          0.0  
1                    1.0         18.75                   2.5          0.0  
2                    1.0         31.30                   2.5          0.0  
3                    1.0         17.00                   2.5          0.0  
4                    1.0         16.10                   2.5          0.0

In [5]:
df.dtypes

VendorID                          int32
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag                  str
PULocationID                      int32
DOLocationID                      int32
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
Airport_fee                     float64
dtype: object

In [6]:
len(df.columns)

19

In [7]:
len(df)

2964624

In [14]:
df.tpep_dropoff_datetime.max()

Timestamp('2024-02-02 13:56:52')

In [15]:
df.tpep_pickup_datetime.max()

Timestamp('2024-02-01 00:01:15')

In [8]:
# Here’s a simple list of the MLOps Zoomcamp January 2024 NYC Yellow Taxi homework questions 
# with their **expected answers**:

# 1. Number of records in January 2024 dataset 
# # → ~2,964,624
# 2. Trip duration standard deviation
# # → ~34.85 minutes
# 3. Percentage of trips with duration 1–60 minutes 
# # → ~98%
# 4. Number of features after creating PU_DO and using DictVectorizer 
# → ~515
# 5. Training RMSE (Linear Regression) 
# → ~7.65
#. Validation RMSE (February 2024 data) 
# → ~7.8


In [9]:
# Question: Read the data for January. How many columns are there?
# 1. Number of records in January 2024 dataset 
# # → ~2,964,624
first_of_jan = np.datetime64('2024-01-01', 'us').astype('datetime64[us]')
print('First of January: {}'.format(first_of_jan))
print()
last_of_jan = np.datetime64('2024-01-31', 'us').astype('datetime64[us]')
print('Last of January: {}'.format(last_of_jan))
print()
df['tpep_dropoff_datetime'] = df['tpep_dropoff_datetime'].astype('datetime64[us]')
df['tpep_pickup_datetime'] = df['tpep_pickup_datetime'].astype('datetime64[us]')

df['duration'] = (df['tpep_dropoff_datetime'] - df['tpep_pickup_datetime']).dt.total_seconds() / 60
print(df['duration'])

# January dataset
df_Jan = df[(df['tpep_dropoff_datetime'] >= first_of_jan)&\
    (df['tpep_dropoff_datetime'] <= last_of_jan)]

# Required Answer:
print('There are a total of {} columns in the January dataset.'.format(len(df_Jan.columns)))


First of January: 2024-01-01T00:00:00.000000

Last of January: 2024-01-31T00:00:00.000000

0          19.800000
1           6.600000
2          17.916667
3           8.300000
4           6.100000
             ...    
2964619     8.616667
2964620    14.750000
2964621    19.000000
2964622    17.850000
2964623    15.083333
Name: duration, Length: 2964624, dtype: float64
There are a total of 20 columns in the January dataset.


In [10]:
df_Jan

VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0               2  2024-01-01 00:57:55   2024-01-01 01:17:43              1.0   
1               1  2024-01-01 00:03:00   2024-01-01 00:09:36              1.0   
2               1  2024-01-01 00:17:06   2024-01-01 00:35:01              1.0   
3               1  2024-01-01 00:36:38   2024-01-01 00:44:56              1.0   
4               1  2024-01-01 00:46:51   2024-01-01 00:52:57              1.0   
...           ...                  ...                   ...              ...   
2961109         2  2024-01-30 23:05:29   2024-01-30 23:21:02              NaN   
2961110         2  2024-01-30 23:27:15   2024-01-30 23:34:56              NaN   
2961111         1  2024-01-30 23:19:23   2024-01-30 23:26:12              NaN   
2961112         1  2024-01-30 23:13:08   2024-01-30 23:21:45              NaN   
2961113         2  2024-01-30 23:12:57   2024-01-30 23:24:25              NaN   

         trip_distance  RatecodeID store_and_fwd_flag  PULocationID  \
0                 1.72         1.0                  N           186   
1                 1.80         1.0                  N           140   
2                 4.70         1.0                  N           236   
3                 1.40         1.0                  N            79   
4                 0.80         1.0                  N           211   
...                ...         ...                ...           ...   
2961109           1.79         NaN                NaN           234   
2961110           1.13         NaN                NaN           255   
2961111           1.20         NaN                NaN            48   
2961112           0.00         NaN                NaN            79   
2961113           2.23         NaN                NaN           158   

         DOLocationID  payment_type  fare_amount  extra  mta_tax  tip_amount  \
0                  79             2        17.70    1.0      0.5        0.00   
1                 236             1        10.00    3.5      0.5        3.75   
2                  79             1        23.30    3.5      0.5        3.00   
3                 211             1        10.00    3.5      0.5        2.00   
4                 148             1         7.90    3.5      0.5        3.20   
...               ...           ...          ...    ...      ...         ...   
2961109           137             0         6.83    0.0      0.5        0.00   
2961110           112             0         9.33    0.0      0.5        0.00   
2961111           162             0         7.90    1.0      0.5        1.94   
2961112            45             0        11.00    1.0      0.5        2.40   
2961113           144             0        13.98    0.0      0.5        0.00   

         tolls_amount  improvement_surcharge  total_amount  \
0                 0.0                    1.0         22.70   
1                 0.0                    1.0         18.75   
2                 0.0                    1.0         31.30   
3                 0.0                    1.0         17.00   
4                 0.0                    1.0         16.10   
...               ...                    ...           ...   
2961109           0.0                    1.0         10.83   
2961110           0.0                    1.0         10.83   
2961111           0.0                    1.0         14.84   
2961112           0.0                    1.0         20.40   
2961113           0.0                    1.0         17.98   

         congestion_surcharge  Airport_fee   duration  
0                         2.5          0.0  19.800000  
1                         2.5          0.0   6.600000  
2                         2.5          0.0  17.916667  
3                         2.5          0.0   8.300000  
4                         2.5          0.0   6.100000  
...                       ...          ...        ...  
2961109                   NaN          NaN  15.550000  
2961110                   NaN

In [11]:
# Q2: Computing Duration
# 2. Trip duration standard deviation
# # → ~34.85 minutes
# You must calculate the duration of the trips in minutes.
# Question: What is the standard deviation of the trips duration in January?
# Expected Logic:
# Subtract tpep_pickup_datetime from tpep_dropoff_datetime.
# Convert the resulting timedelta to total minutes.

# Load your data (assuming it's already in a DataFrame 'df')
# Ensure columns are datetime objects first
first_of_jan = np.datetime64('2024-01-01', 'us').astype('datetime64[us]')
print('first of January is {}'.format(first_of_jan))
print()
last_of_jan = np.datetime64('2024-01-31', 'us').astype('datetime64[us]')
print()
print('last of January is {}'.format(last_of_jan))
print()
print('df at one drop off time is {}'.format(df['tpep_dropoff_datetime'].iloc[0]))

df['tpep_dropoff_datetime'] = df['tpep_dropoff_datetime'].astype('datetime64[us]')
df['tpep_pickup_datetime'] = df['tpep_pickup_datetime'].astype('datetime64[us]')

# 1. Calculate Duration:
df['duration'] = (df['tpep_dropoff_datetime'] - df['tpep_pickup_datetime']).dt.total_seconds() / 60
print(df['duration'])

# Extract the January Dataset:
df_Jan = df[(df['tpep_dropoff_datetime'] >= first_of_jan)&\
    (df['tpep_dropoff_datetime'] <= last_of_jan)]

# Calculate the standard deviation of duration for January dataset:
print('The standard deviation of duration is {}'.format(round(df_Jan['duration'].std(), 2)))


first of January is 2024-01-01T00:00:00.000000


last of January is 2024-01-31T00:00:00.000000

df at one drop off time is 2024-01-01 01:17:43
0          19.800000
1           6.600000
2          17.916667
3           8.300000
4           6.100000
             ...    
2964619     8.616667
2964620    14.750000
2964621    19.000000
2964622    17.850000
2964623    15.083333
Name: duration, Length: 2964624, dtype: float64
The standard deviation of duration is 33.98


In [12]:
# Q3: Dropping Outliers
# To clean the data, you need to filter the duration to only include trips between 1 and 60 minutes (inclusive).
# 3. Percentage of trips with duration 1–60 minutes 
# # → ~98%
# Question: What fraction of the records left after you dropped the outliers?
# Expected Answer: Approximately 98%.
prop = 100 * len(df_Jan[df_Jan['duration'].between(1, 60)]) / len(df_Jan)
print('The percentage of trips with duration between 1 and 60 minutes is {}%'.format(round(prop)))

The percentage of trips with duration between 1 and 60 minutes is 98%


#### Begin An Aside from ChatGPT
#### NNG The following is useful for Question four below, as it explains DictVectorizer's Usage and Advantage over get_dummies:

Great — this is an important ML engineering concept.

#### What Is `DictVectorizer`?

`DictVectorizer` is from:

```python
from sklearn.feature_extraction import DictVectorizer
```

It converts **a list of Python dictionaries** into a **numerical feature matrix**.

It is mainly used for:

* Categorical encoding
* One-hot encoding
* Production ML pipelines
* Sparse feature generation
---

#### Why It’s Used in MLOps Zoomcamp

Because it:

* Automatically one-hot encodes categorical features
* Returns a **sparse matrix** (memory efficient)
* Keeps a stable feature mapping between train and validation
* Is easy to serialize with the model
---

#### Step 1: What Your DataFrame Looks Like

Example DataFrame:

```python
import pandas as pd

df = pd.DataFrame({
    "PUlocationID": ["43", "74", "132"],
    "DOlocationID": ["151", "43", "75"]
})

print(df)
```

Output:

```
  PUlocationID DOlocationID
0           43          151
1           74           43
2          132           75
```

---

#### Step 2: Convert DataFrame to Dictionary Format

This is the **exact required format**:

```python
dicts = df.to_dict(orient="records")
print(dicts)
```

Output:

```
[
 {'PUlocationID': '43', 'DOlocationID': '151'},
 {'PUlocationID': '74', 'DOlocationID': '43'},
 {'PUlocationID': '132', 'DOlocationID': '75'}
]
```

Important:

* It becomes a **list**
* Each row becomes a **dictionary**
* Keys = column names
* Values = category values (must be strings)

This format is what `DictVectorizer` expects.
---

#### Step 3: Apply `DictVectorizer`

```python
dv = DictVectorizer()

X = dv.fit_transform(dicts)
```

Now `X` is a **sparse matrix**.
---

#### What Features Look Like Internally

Check feature names:

```python
dv.feature_names_
```
Output:
```
[
 'DOlocationID=151',
 'DOlocationID=43',
 'DOlocationID=75',
 'PUlocationID=132',
 'PUlocationID=43',
 'PUlocationID=74'
]
```
Notice:
Each unique value becomes:
```
column_name=value
```
So:
* `PUlocationID=43`
* `DOlocationID=43`
are **different features**
---
#### What the Matrix Looks Like

If converted to dense form (just to see it):

```python
X.toarray()
```
You’d see something like:
```
[[0 0 0 0 1 0]
 [0 1 0 0 0 1]
 [0 0 1 1 0 0]]
```
Each row has:
* One 1 for PU
* One 1 for DO
* Everything else is 0
---
#### Why Convert to String First?
In the taxi homework:
```python
df[categorical] = df[categorical].fillna(-1).astype(int).astype(str)
```
Why?
Because:
* IDs are categorical, not numeric quantities
* `DictVectorizer` treats numbers differently
* Converting to string forces categorical treatment
---
#### Train vs Validation Behavior

```python
dv = DictVectorizer()
X_train = dv.fit_transform(train_dicts)
X_val = dv.transform(val_dicts)
```

Important:

* `fit` learns feature mapping
* `transform` uses the same mapping
* Unseen categories are ignored safely

This is why it's production-safe.
---
#### Summary

`DictVectorizer`:
* Takes → `List[Dict[str, value]]`
* Produces → Sparse matrix
* Creates features like → `"column=value"`
* Is safer than `pd.get_dummies()` for ML pipelines
* Keeps feature consistency across datasets
---

If you'd like, I can also show how `DictVectorizer` handles unseen categories — that’s a very common interview question.
---
#### How Ignored Categories are Treated At Prediction Time 

Perfect — let’s look at how `DictVectorizer` handles **unseen categories**, which is a very important point for production ML.
---

#### Scenario

Suppose you have **training data** with only some location IDs:

```python
from sklearn.feature_extraction import DictVectorizer

# Training data
train_dicts = [
    {'PUlocationID': '43', 'DOlocationID': '151'},
    {'PUlocationID': '74', 'DOlocationID': '43'},
]

dv = DictVectorizer()
X_train = dv.fit_transform(train_dicts)

print("Feature names:", dv.feature_names_)
```

**Output:**

```
Feature names: ['DOlocationID=43', 'DOlocationID=151', 'PUlocationID=43', 'PUlocationID=74']
```

So `DictVectorizer` only learned features present in the **training set**.

---

### Validation / New Data with Unseen Category

Suppose your **validation data** has a new category:

```python
val_dicts = [
    {'PUlocationID': '132', 'DOlocationID': '151'},  # PU=132 unseen
    {'PUlocationID': '43', 'DOlocationID': '999'},   # DO=999 unseen
]

X_val = dv.transform(val_dicts)
print(X_val.toarray())
```

**Output (dense for clarity):**

```
[[0 1 0 0]  # PU=132 is unseen → ignored
 [0 0 1 0]]  # DO=999 is unseen → ignored
```

### ✅ Key Points:

1. **Unseen categories are ignored**

   * `PUlocationID=132` or `DOlocationID=999` do not appear in training features → they are silently dropped.
2. **Matrix shape is consistent**

   * `X_val.shape[1] == X_train.shape[1]`
3. **No errors**

   * Unlike `pd.get_dummies()` without column alignment, which can break pipelines.

---

# Why This Matters

* In production, your model may see **new pickup/dropoff locations**.
* Using `DictVectorizer` ensures:

  * Safe handling of unseen categories
  * Fixed feature order
  * Sparse memory efficiency

---

# Optional Handling of Unseen Categories

If you want to **catch unseen categories**, you can inspect the dictionaries:

```python
for d in val_dicts:
    for k, v in d.items():
        if f"{k}={v}" not in dv.feature_names_:
            print(f"Unseen: {k}={v}")
```

Output:
```
Unseen: PUlocationID=132
Unseen: DOlocationID=999
```

This is useful for logging or alerts in production ML pipelines.

#### End Aside from Chat ChatGPT


In [ ]:
# Q4: One-Hot Encoding
# You will use PULocationID and DOLocationID as features. Since these are IDs, they must be treated 
# as categorical strings.
# Question: What is the dimensionality of the feature matrix (number of columns) after one-hot 
# encoding?
# Expected Logic: 1.  Cast IDs to strings.
# 2.  Turn the dataframe into a list of dictionaries (i.e. here each row is a dictionary in the list).
# 3.  Fit a DictVectorizer.
#Expected Answer: Approximately 515 (This varies slightly by year/dataset version)//.
Y = df_Jan[df_Jan['duration'].between(1, 60)]
u_pu = Y['PULocationID'].unique()
u_do = Y['DOLocationID'].unique()
print('Unique PULocationID values: {}'.format(len(u_pu)))
print()
print('Unique DOLocationID values: {}'.format(len(u_do)))   

X = Y[['duration', 'PULocationID', 'DOLocationID']].copy()
X['PULocationID'] = X['PULocationID'].fillna(-1)
X['DOLocationID'] = X['DOLocationID'].fillna(-1)
X_encoded = pd.get_dummies(X, columns=['PULocationID', 'DOLocationID'])
print()
print('The number of columns after one-hot encoding is {}'.format(len(X_encoded.columns)))                                                                                                                             

Unique PULocationID values: 257

Unique DOLocationID values: 261

The number of columns after one-hot encoding is 519


In [14]:
# Q5: Training a Model
# Train a plain Linear Regression model with default parameters.
# Question: What is the RMSE on the training data?
# Expected Answer: Approximately 7.64.
# 5. Training RMSE (Linear Regression) 
# → ~7.65

print('Data types of columns in df are: ')
print()
print(df.dtypes)

df_Jan_encoded.drop(columns = ['tpep_pickup_datetime',\
    'tpep_dropoff_datetime',\
        'store_and_fwd_flag'], inplace=True)

df_Jan_encoded

Data types of columns in df are: 

VendorID                          int32
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag                  str
PULocationID                      int32
DOLocationID                      int32
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
Airport_fee                     float64
duration                        float64
dtype: object


NameError: name 'df_Jan_encoded' is not defined

In [15]:
df_Jan_encoded.dropna(inplace=True)

df_Jan_encoded

: 

In [ ]:
# Q6: Evaluating the Model
# Apply the model to the February dataset (the validation set).
#Question: What is the RMSE on the validation data?
# Expected Answer: Approximately 7.81.

